export const projects = [
  {
    title: "HealthCare AI Assistant",
    description:
      "Assistant IA pour l'aide au diagnostic médical utilisant le deep learning",
    technologies: ["Python", "TensorFlow", "React", "FastAPI"],
    category: "Intelligence Artificielle",
    year: "2024",
    team: 4,
    image: "🏥",
    achievements: ["Prix innovation", "Partenariat CHU"],
  },
  {
    title: "SecureBank Mobile",
    description:
      "Application bancaire mobile avec authentification biométrique avancée",
    technologies: ["React Native", "Node.js", "MongoDB", "Blockchain"],
    category: "Cybersécurité",
    year: "2024",
    team: 5,
    image: "🏦",
    achievements: ["Mention très bien", "Stage BNP Paribas"],
  },
  {
    title: "EcoTrack Platform",
    description: "Plateforme de suivi d'empreinte carbone pour entreprises",
    technologies: ["Vue.js", "Django", "PostgreSQL", "Docker"],
    category: "Développement Web",
    year: "2023",
    team: 3,
    image: "🌱",
    achievements: ["Prix développement durable", "Startup créée"],
  },
  {
    title: "GameVerse VR",
    description: "Jeu multijoueur en réalité virtuelle avec physique avancée",
    technologies: ["Unity", "C#", "Photon", "Oculus SDK"],
    category: "Game Development",
    year: "2023",
    team: 6,
    image: "🎮",
    achievements: ["Finaliste concours", "10k+ téléchargements"],
  },
  {
    title: "SmartCity Dashboard",
    description:
      "Tableau de bord intelligent pour la gestion urbaine en temps réel",
    technologies: ["Angular", "Spring Boot", "Kafka", "Elasticsearch"],
    category: "Big Data",
    year: "2024",
    team: 4,
    image: "🏙️",
    achievements: ["Partenariat mairie", "Déploiement pilote"],
  },
  {
    title: "CryptoWallet Pro",
    description: "Portefeuille de cryptomonnaies avec trading automatisé",
    technologies: ["Flutter", "Rust", "WebAssembly", "Blockchain"],
    category: "Mobile & Blockchain",
    year: "2023",
    team: 3,
    image: "💰",
    achievements: ["Prix innovation", "Levée de fonds"],
  },
];
